/* eslint-disable react/no-unescaped-entities */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <head>
  <style>
@import url('https://fonts.cdnfonts.com/css/led-digital-7');
</style>
<link href="https://fonts.cdnfonts.com/css/led-digital-7" rel="stylesheet"/>
                
  </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
